version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: oruel-relay-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: oruel
      POSTGRES_PASSWORD: oruel_password
      POSTGRES_DB: oruel_relay
    ports:
      - "5433:5432"
    volumes:
      - oruel_relay_pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: oruel-relay-app
    restart: unless-stopped
    ports:
      - "80:4000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://oruel:oruel_password@postgres:5432/oruel_relay?schema=public
    depends_on:
      - postgres

volumes:
  oruel_relay_pgdata:
